pipelines:
  Build_pizza:
    group: pizza
    label_template: "${repository[:7]}"
    materials:
      repository:
        git: git@github.com:sebastianhutter/pizza-api.git
    environment_variables:
      RANCHER_URL: https://rancher.hutter.cloud:8080
      # you can get the service id from the api view in rancher
      SERVICE_NAME: pizza
    stages:
      - Build:
          jobs:
            build:
              artifacts:
               - build:
                   source: image_version
               - build:
                   source: image_name
              tasks:
               - exec:
                   command: make
                   arguments:
                    - build_latest
               - exec:
                   command: make
                   arguments:
                    - build_commit
               - exec:
                   command: make
                   arguments:
                    - push_latest
               - exec:
                   command: make
                   arguments:
                    - push_commit
  Deploy_pizza:
    group: pizza
    materials:
      build:
        pipeline: Build_pizza
        stage: build
    environment_variables:
      RANCHER_URL: https://rancher.hutter.cloud:8080
      # you can get the service id from the api view in rancher
      SERVICE_NAME: pizza
    stages:
      - Deploy:
          jobs:
            deploy:
              tasks:
               - fetch:
                  pipeline: Build_pizza
                  stage: build
                  job: build
                  is_file: yes
                  source: image_version
               - fetch:
                  pipeline: Build_pizza
                  stage: build
                  job: build
                  is_file: yes
                  source: image_name
               - script: |
                   export image_version=$(cat image_version)
                   export image_name=$(cat image_name)
                   rancher_upgrade.sh ${SERVICE_NAME} ${image_name} ${image_version}